:asciidoctor:
  :eruby: erubis
  :attributes:
    source-highlighter: prettify
profiles:
  development:
  production:
    base_url: http://www.bleathem.ca/
    deploy:
      host: bleathem.ca
      path: /home/bleathem/bleathem.ca/
      exclude: talks
  stage:
    base_url: http://stage.bleathem.ca/
    deploy:
      host: www.bleathem.ca
      path: /home/bleathem/stage.bleathem.ca/
      exclude: talks
